use std::io::Cursor;

use laboratories::{InputParseError, count_beam_splits_and_timelines, parse_grid};

fn assert_counts<T: AsRef<[u8]>>(
    s: T,
    expected_splits: usize,
    expected_timelines: usize,
) -> Result<(), InputParseError> {
    let mut grid = parse_grid(Cursor::new(s))?;
    let (splits, timelines) = count_beam_splits_and_timelines(&mut grid);
    assert_eq!(splits, expected_splits);
    assert_eq!(timelines, expected_timelines);

    Ok(())
}

#[test]
fn test_counts() -> Result<(), InputParseError> {
    assert_counts(".......S.......", 0, 1)?;
    assert_counts(
        ".......S.......
            ...............
            .......^.......",
        1,
        2,
    )?;
    assert_counts(
        ".......S.......
            ...............
            .......^.......
            ...............
            ......^.^......",
        3,
        4,
    )?;
    assert_counts(
        ".......S.......
            ...............
            .......^.......
            ...............
            ......^........
            ...............
            .....^.^.......
            ...............",
        4,
        5,
    )?;
    assert_counts(
        ".......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............",
        6,
        8,
    )?;
    assert_counts(
        ".......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............",
        21,
        40,
    )?;

    Ok(())
}
